CREATE TABLE `sdu_org` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  c_org_code char(3) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  c_nhs_area varchar(255) DEFAULT NULL,
  c_phe_centre varchar(255) DEFAULT NULL,
  c_region varchar(255) DEFAULT NULL,
  account_type varchar(255) DEFAULT NULL,
  c_sdmp varchar(255) DEFAULT NULL,
  c_adaptation varchar(255) DEFAULT NULL,
  c_on_track_34_pct varchar(255) DEFAULT NULL,
   c_healthy_tp varchar(255) DEFAULT NULL,
  c_gcc varchar(255) DEFAULT NULL,
   c_sr_score varchar(255) DEFAULT NULL,
  c_sr_pct varchar(255) DEFAULT NULL,
  c_nrg varchar(255) DEFAULT NULL,
   c_nrg_fte varchar(255) DEFAULT NULL,
   c_water varchar(255) DEFAULT NULL,
   c_water_fte varchar(255) DEFAULT NULL,
   c_waste varchar(255) DEFAULT NULL,
   c_waste_change varchar(255) DEFAULT NULL,
   `account_id` bigint(20) NULL,
  PRIMARY KEY (`id`)
) 
