apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-configmap
  namespace: default
data:
  SERVER_SERVLET_CONTEXT_PATH: {{ .Values.rest.contextPath | quote }}
  KEYCLOAK_REALM: {{ .Values.keycloak.realm | quote }}
  KEYCLOAK_AUTH-SERVER-URL: {{ .Values.keycloak.authServerUrl | quote }}
  KEYCLOAK_RESOURCE: {{ .Values.keycloak.resource | quote }}
  KEYCLOAK_ENABLED: {{ .Values.keycloak.enabled | quote }}
  {{- if and .Values.database.datasourceDriverClassName .Values.database.datasourceUrl }}
  SPRING_DATASOURCE_DRIVER-CLASS-NAME: {{ .Values.database.datasourceDriverClassName | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.database.datasourceUrl | quote }}
  {{- end }}
  SPRING_JPA_HIBERNATE_DDL-AUTO: {{ .Values.jpa.hibernate.ddlAuto | quote }}
  SPRING_JPA_SHOW-SQL: {{ .Values.jpa.showSql | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: {{ .Values.jpa.properties.hibernate.formatSql | quote }}
  SRP_APPLICATION_BASE-URI: {{ .Values.srp.application.baseUri | quote }}
  {{- if and .Values.srp.application.period }}
  SRP_APPLICATION_PERIOD: {{ .Values.srp.application.period | quote }}
  {{- end }}
  {{- if and .Values.srp.cors.allowedOrigins }}
  SRP_CORS_ALLOWED-ORIGINS: {{ .Values.srp.cors.allowedOrigins | quote }}
  {{- end }}
  {{- if and .Values.srp.cors.allowedMethods }}
  SRP_CORS_ALLOWED-METHODS: {{ .Values.srp.cors.allowedMethods | quote }}
  {{- end }}
  {{- if and .Values.srp.cors.allowedHeaders }}
  SRP_CORS_ALLOWED-HEADERS: {{ .Values.srp.cors.allowedHeaders | quote }}
  {{- end }}
  {{- if and .Values.srp.cors.allowCredentials }}
  SRP_CORS_ALLOW-CREDENTIALS: {{ .Values.srp.cors.allowCredentials | quote }}
  {{- end }}
