update SR_CAT set questions = 'SDMP_CRMP,SDMP_BOARD_REVIEW_WITHIN_12_MONTHS,SDMP_MISSION_STATEMENT,SDMP_INC_PROCUREMENT,HEALTHY_TRANSPORT_PLAN,PROMOTE_HEALTHY_TRAVEL,QUANT_TRAVEL_IMPACTS,PROC_SUPPLIER_SUSTAINABILITY,PROC_SUPPLIER_ENGAGEMENT,STRATEGIC_SUSTAINABILITY_PARTNERS,LAST_GCC_DATE,LAST_GCC_SCORE,SDG_STARTING,SDG_CLEAR,PROMOTE_SUSTAINABILITY_TO_STAFF,MOD_SLAVERY,SIA,SOCIAL_VALUE,BIODIVERSITY' 
where id = 55;

update SR_QUESTION set label = 'If you have established strategic partnerships with other organisations on sustainability, who are they?' where name  = 'STRATEGIC_SUSTAINABILITY_PARTNERS';

delete from SR_QUESTION where name = 'STRATEGIC_SUSTAINABILITY_PARTNERSHIPS';
