package digital.srp.sreport.model;

public enum WeightingFactors {
    ENERGY,
    GAS,
    ELEC,
    OIL,
    COAL,
    BIZ_SVCS,
    CONSTRUCTION,
    CATERING,
    FREIGHT,
    ICT,
    FUEL_CHEM_AND_GASES,
    MED_INSTRUMENTS,
    OTHER_MANUFACTURING,
    OTHER_PROCURMENT,
    PAPER,
    PHARMA,
    WASTE,
    WATER,
    BIZ_TRAVEL,
    COMMISSIONING,
    ANAESTHETIC_GASES, PATIENT_TRAVEL, VISITOR_TRAVEL, STAFF_TRAVEL
}
